### PR TITLE
Entrypoint.d

### PR DESCRIPTION
**Pull request by papey**
This PR adds an entrypoint.d mechanism to PHP images.

This feature will allow users to put their own scripts and executable in a directory `/entrypoint.d`. A script, fires at each launch will exec all the files marked as executable from this directory.

If it's look go to you, i will write the documentation for this feature.

### CODE REVIEW

**Review by athoune — APPROVED** [review]
It's clear and explicit.

**Comment by beavis69** [comment]
If you add that feature, i think /usr/local/bin/config_msmtp.sh from ( https://github.com/factorysh/docker-php/blob/master/entrypoint.sh ) must use this feature too.

Most of the time, i rewrite the entrypoint.sh because i need a custom msmtp config file.

And also we also need to manage entrypoint.d.sh scripts execution order.

**Comment by papey** [comment]
MSMTP config moved inside entrypoint.d (`00-msmtp.sh`).

Files sorted alphabetically using `sort`

**Comment by papey** [comment]
Documentation added, looking for reviews. Thanks.

**Review by athoune — APPROVED** [review]

**Review by beavis69 — APPROVED** [review]

**Pull request merged**
